function appendLog(logPath, meta, changes)
%appendLog Append a Markdown section if changes are non-empty.

    if model_log.isEmptyChanges(changes)
        return;
    end

    section = model_log.formatLogSection(meta, changes);

    if ~isfile(logPath)
        header = sprintf([ ...
            '# Simulink Model Log: %s\n\n' ...
            'Auto-generated by model_log. Each save with changes appends a section.\n\n'], ...
            meta.modelName);
        localWriteUtf8(logPath, [header section], false);
    else
        localWriteUtf8(logPath, section, true);
    end
end

function localWriteUtf8(path, text, appendMode)
    if appendMode
        fid = fopen(path, 'a', 'n', 'UTF-8');
    else
        fid = fopen(path, 'w', 'n', 'UTF-8');
    end
    if fid < 0
        error('model_log:appendLog:OpenFailed', ...
            'Cannot open Log file: %s', path);
    end
    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fwrite(fid, text, 'char');
end
