function tf = isEmptyChanges(changes)
%ISEMPTYCHANGES True when a diff result has no structural or parameter changes.

    tf = isempty(changes.blockAdded) && ...
        isempty(changes.blockRemoved) && ...
        isempty(changes.blockTypeChanged) && ...
        isempty(changes.paramChanged) && ...
        isempty(changes.lineAdded) && ...
        isempty(changes.lineRemoved) && ...
        localEmptyField(changes, 'chartAdded') && ...
        localEmptyField(changes, 'chartRemoved') && ...
        localEmptyField(changes, 'stateAdded') && ...
        localEmptyField(changes, 'stateRemoved') && ...
        localEmptyField(changes, 'stateChanged') && ...
        localEmptyField(changes, 'transitionAdded') && ...
        localEmptyField(changes, 'transitionRemoved') && ...
        localEmptyField(changes, 'transitionChanged') && ...
        localEmptyField(changes, 'dataAdded') && ...
        localEmptyField(changes, 'dataRemoved') && ...
        localEmptyField(changes, 'dataChanged');
end

function tf = localEmptyField(changes, name)
    if ~isfield(changes, name)
        tf = true;
        return;
    end
    tf = isempty(changes.(name));
end
